#!/bin/bash
# activate.sh
if [[ -z "${BONSAI_EXE_PATH}" ]]; then
    echo "Error! Cannot have multiple bonsai environments activated at the same time. Please deactivate the previous environment before activating the new one."
    exit 125
fi
BONSAI_ENV_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"
export BONSAI_EXE_PATH="$BONSAI_ENV_DIR/Bonsai.exe"
export ORIGINAL_PS1="$PS1"
export PS1="($(basename "$BONSAI_ENV_DIR")) $PS1"
alias bonsai='mono "$BONSAI_EXE_PATH"'
alias bonsai-clean='GTK_DATA_PREFIX= mono "$BONSAI_EXE_PATH"'
alias deactivate='source "$BONSAI_ENV_DIR"/deactivate'
echo "Activated bonsai environment in $BONSAI_ENV_DIR"